### ISSUE TITLE
Crimespree lobby nonfunctional

### ISSUE THREAD

**Issue by Forspan** [polarathene/biglobby#37] opened 2017-04-25 16:40 UTC
Anyone attempting to join a big lobby game in crimespree will crash. The host has no issues starting on his own. My own crash.txt details below:

Application has crashed: access violation

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 

-------------------------------

Current thread: Main
Script stack:
                        send()  lib/network/base/networkpeer.lua:1024               
                        send()  @mods/biglobby/lua/lib/network/base/_networkpeer.lua:14  
               send_to_peers()  lib/network/base/basenetworksession.lua:659         
_send_crime_spree_level_to_peers()  lib/managers/crimespreemanager.lua:1538             
            on_entered_lobby()  lib/managers/crimespreemanager.lua:1482             
              on_enter_lobby()  lib/managers/menumanagerpd2.lua:55                  
                          cb()  lib/network/matchmaking/networkmatchmakingsteam.lua:795  
       on_join_request_reply()  lib/network/base/clientnetworksession.lua:149       
       on_join_request_reply()  @mods/biglobby/lua/lib/network/base/_clientnetworksession.lua:29  
                                @mods/biglobby/lua/lib/network/base/handlers/_connectionnetworkhandler.lua:17  

-------------------------------

System information:
	Application version : 1.68.209
	CPU : Intel(R) Core(TM) i5-2500K CPU @ 3.30GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce GTX 1050 / nvd3dum.dll[21.21.13.7653]
	Language : @ID94cca2fdaccfc2cd@
	Memory :     8089MB 152KB
	OS : 6.2.9200 () 0x300-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : ASUSTeK (Speakers (ASUS Xonar DG Audio Device))

**Comment by polarathene** [comment] 2017-04-26 04:04
Hi there, thanks for the report. I no longer play this game, I'll try update my mod to support it if it's not too much effort :) If it's like it usually is should be fixed by tomorrow, otherwise may need to get another modder to help contribute a fix. I'll let you know when I publish an update that you can test.

**Comment by polarathene** [comment] 2017-04-26 04:54
@Forspan Hi there, [I've released v2.39 here](https://github.com/polarathene/biglobby/releases/tag/v2.39), could you give it a try and let me know if it works for you? Thanks :)

**Comment by Forspan** [comment] 2017-04-26 11:34
Thanks for the quick reply! I tried it with my friend but unfortunately we ran into a different problem this time as I tried to connect to his lobby:

Application has crashed: C++ exception
[string "lib/managers/menu/crimespreemissionsmenucom..."]:628: attempt to index field 'level' (a nil value)



SCRIPT STACK



-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        


-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.68.209
	CPU : Intel(R) Core(TM) i5-2500K CPU @ 3.30GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce GTX 1050 / nvd3dum.dll[21.21.13.7653]
	Language : @ID94cca2fdaccfc2cd@
	Memory :     8089MB 152KB
	OS : 6.2.9200 () 0x300-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : ASUSTeK (Speakers (ASUS Xonar DG Audio Device))

**Comment by polarathene** [comment] 2017-04-26 13:19
@Forspan I don't touch that code with my mod, whatever the crimespree thing is(since I haven't played in many months) is causing the crash. I had a quick look at the file it mentions(the line number isn't correct), seems that the cause is UI related.

I don't have time to fix this unfortunately. An active community modder may be able to assist, chances are there is a hardcoded limit to 4 players like other UI code that needs to be patched. The change may not be in the file that's in your crash report, it could be in any of the UI files. Assuming I'm right, if you can find an active community modder who has the time to find the code and change it, it shouldn't take them too long to do. My mod code is nicely written with comments to make it easy for others to understand.

I'm happy to provide any advice and update the mod code if someone else provides the UI code fix.

**Comment by polarathene** [comment] 2017-04-26 13:52
I just noticed while addressing another issue that I forgot to add a prefix to the biglobby receiver for the new crimespree method, also related to level. If lucky it's not a UI bug and this will fix it for you :)

Please try [v2.40](https://github.com/polarathene/biglobby/releases/tag/v2.40).

**Comment by Forspan** [comment] 2017-04-26 15:48
We tried v2.40 and while the client manages to connect and appears normally in the lobby for the host, it crashes for the client before they'd see the lobby view themselves.

Ergo it may very well be an UI bug like you suspect. >_<

Edit: Ah yes, the crash.txt remains the same as before.

**Comment by rockr230** [comment] 2017-04-26 19:58
@Forspan Try starting a crime spree heist, and have your friends join in during the preplanning. That's the work around my friends and I have been using. Oddly, when we go back to the lobby, nobody crashes. Make sure any clients joining already have an ongoing crime spree, so they can gain ranks.

**Comment by polarathene** [comment] 2017-04-27 00:24
@rockr230 That's interesting, definitely sounds like it could be a UI bug then in the lobby screen? I'll leave the issue open in case anyone wants to contribute a bug fix or runs into the problem and needs to know how to work around it. Cheers!

**Comment by Shad0wlife** [comment] 2017-12-25 19:34
Ok, the crash happens because "level" is nil. Could that be because in a crimespree lobby, there is no level selected until you... well select one of the 3 in the corner?
Question to experienced devs: a regular lobby ALWAYS has a mission linked to it, either the one it was opened with or the last one played, right? Because maybe this is not the case with a crimespree lobby (due to the different heist selection method).

**Comment by polarathene** [comment] 2017-12-26 23:20
@Shad0wlife I haven't dealt with the game codebase or modding PD2 in a long time, so I can't answer your questions.
Crimespree feature came well after BigLobby was made and while it was going into maintenance mode. 

PR is welcome for supporting it if it's important to users.

**Comment by Shad0wlife** [comment] 2017-12-26 23:40
I think this can be closed. Fixed it in one of the 2 prs I submitted. At least I'm currently playing a crimespree with friends and biglobby installed and we even tested extra bots, works too in crimespree.

EDIT: Seems that the crash can still happen (with the level being nil), but not ALWAYS on join. Will investigate.

**Comment by polarathene** [comment] 2017-12-27 08:41
I'll close this issue as your PR resolves it. The other bug you mention in your edit can be PR'd or raised as a separate issue :) Thanks!

**Closed as completed by polarathene** 2017-12-27 08:41 UTC
Labels: help wanted
