### ISSUE TITLE
Unable to continue with any heist with this script_path

### ISSUE THREAD

**Issue by MyNameisBechamel** [polarathene/biglobby#33] opened 2017-01-10 12:14 UTC
This script causes a small crash upon playing any heist for 4 minutes. No other mods were conflicting it.

Application has crashed: C++ exception
[string "lib/managers/group_ai_states/groupaistatebe..."]:414: attempt to perform arithmetic on a nil value

**Comment by polarathene** [comment] 2017-01-11 00:38
Does the BLT log have anything about biglobby errors?

What version of BigLobby are you using for BLT mod and pdmod?

**Comment by MyNameisBechamel** [comment] 2017-01-11 08:36
Not quite sure.
----------------------------------------------------------------------

Wed Jan 11 02:32:55 2017


Application has crashed: C++ exception
[string "lib/managers/group_ai_states/groupaistatebe..."]:414: attempt to perform arithmetic on a nil value



SCRIPT STACK



-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlFreeHeap                                         
                         ntdll  (???)     RtlFreeHeap                                         
                         ntdll  (???)     RtlAllocateHeap                                     


-------------------------------

Version 2.37

**Comment by polarathene** [comment] 2017-01-11 08:50
The crashlog isn't too helpful here, it's not referencing a line from biglobby, the line it references in the file is unreliable when it's not from a biglobby file. Your BLT mod log is in the payday 2 game folder in `mods/logs` and should have the date as file name. At the very bottom after a crash should be some information that might help.

I don't have time/resources to run the game myself at the moment. Have you had BigLobby work for you in the past?

**Comment by MyNameisBechamel** [comment] 2017-01-11 09:53
Well well, the great problem was Better Bots mod after all. (even though I checked 'rest of slots will be filled with bots if players have big lobby mod'). ((Upon using both mods together, that crash happens; so I removed it, yet seemed to operate normally.)) 

Honestly, this is my first time downloading this mod. I've never heard of it around the community until B33croft made a video about it.

**Comment by polarathene** [comment] 2017-01-11 12:28
@MyNameisBechamel I don't know what Better Bots is doing to support BigLobby, I don't even know if it needs to do anything? There is a bot config setting in BigLobby settings that lets you say how many bots there should be. Glad to know the crash isn't caused by my mod :)

My mod had a v1 release last March, it had some issues that have been fixed with v2, still a few features left to do when I can find the time as they're not easy ones. This mod is still good if you have enough friends to enjoy it with, otherwise I don't think it's too popular anymore to find lots of lobbies hosted.

Enjoy!

**Closed as completed by polarathene** 2017-01-11 12:28 UTC
