### ISSUE TITLE
Cannot complete the quest on some mission.

### ISSUE THREAD

**Issue by gametoon** [polarathene/biglobby#17] opened 2016-06-28 13:18 UTC
I got stuck on some mission that require all players to do some tasks such as stay in car or stay in the room. The problem occur only when there are more than 4 players. To fix this problem I try to lower max players to 4 players or decrease number of players in my room to 4 (Let the other to custody.) and i can complete it. But Is there any way to fix this problem with out lower number of players in the room?

**Comment by polarathene** [comment] 2016-06-28 21:07
This is one of the bug I know of and want to fix, but it's very hard to work on because I need 4 players to help test it often. Even when I can find enough player for it, often someone get bored and wants to play real game, so have to wait for a new player again before someone else get bored waiting! On top of that I  don't have too much time for doing this, usually only weekend. 

If someone else wants to help work on the code I can advise where to look. Otherwise it could be a while as I need to find the players to help when I have the time to work on the mod.

**Comment by gametoon** [comment] 2016-06-29 16:37
Thanks for info. Can you advice me which file i should take a look?  And Do I need to extract library from game or i can overrided the function without extract them?

**Comment by polarathene** [comment] 2016-06-30 01:38
@gametoon Only network.network_settings asset needs to be extracted for use in pdmod when game updates which usually breaks BigLobby.

Assuming you have PD2 modding experience with Lua, when I was looking into this I believe it was caused by mission script/element data. I never got to finish testing when I was looking into it and I think I lost the snippets/file changes I made(was months ago). There is one I believe that checked player count, I'm not sure if editing the lua file will be the solution. You may need to extract the map data with tools from Last Bullet, find the script data responsible for each level and modify it, then using BeardLib you could make the modification on level load... 

It's a bit of work to find and deal with, let alone get enough people to help test as you develop it :( If someone has time I'm happy to accept PR, otherwise could be months away before I have time to look into it.

**Comment by gametoon** [comment] 2016-07-01 09:36
Okay. Thanks.
ps.Look like u104 broke this mod again.

**Comment by polarathene** [comment] 2016-07-01 13:45
I'll update a fix for U104, but not sure I can keep patching this weekly. It's easy to do normally, I'll add contributor guide on how to do it for the few BigLobby players who want to send in PRs :)

**Comment by polarathene** [comment] 2016-07-09 01:27
Closing as bug is in [v2 checklist](https://github.com/polarathene/biglobby/issues/5).

**Closed as completed by polarathene** 2016-07-09 01:27 UTC
Labels: bug
