### ISSUE TITLE
"Failed joining game"

### ISSUE THREAD

**Issue by Damakun** [polarathene/biglobby#16] opened 2016-06-23 17:05 UTC
So,whenever I try to join a friend's game with Big lobbies turned on,it keeps failing to join the game. We've checked each other's files and found it to be the same. We have no idea what's wrong. Any ideas?

**Comment by polarathene** [comment] 2016-06-23 21:18
@Damakun
- Has the game updated since U102? I haven't been active on it lately.
- Both of you need to have the pdmod file enabled as well as the BLT mod, you should both be using the same version from the releases page, currently 2.0.4--alpha I think, the BLT updater in game does not work for BigLobby.
- If all that is good, remove the pdmod, verify game cache, apply pdmod again. If you enable/disable the BLT mod you may have to restart the game for BLT mods to reload, thus if one of you was playing regular normal game, then turned the BLT mod on in the menu, it wouldn't be ON until BLT mods loaded again(when you start a level or when you restart the game.

If all that checks out try join each others game without the mod on, if that works then might be something wrong in a new update.

**Comment by Damakun** [comment] 2016-06-23 23:55
Do I need to update the mod? Because,I asked my friends and they all have the same version as I do,2.0. The thing is,they could all join each other,the only one that couldn't was me for some reason. 
Also,tried to do the 3rd way,but it didn't work. I asked my friends what date their "en.json" file was modified and theirs s 6/17. For me it's 6/18. Would that affect anything?

**Comment by Damakun** [comment] 2016-06-24 00:05
Also,yeah. The game is at U103 now,with Rust being released.

**Comment by polarathene** [comment] 2016-06-24 02:52
> Do I need to update the mod? Because,I asked my friends and they all have the same version as I do,2.0.

I've been bad and not updated the `mod.txt` version, the mod is still not officially released(not on Last Bullet yet). Last update I made also removed changing version of game, so I guess this prevents the error `Wrong game version` instead you get `Failed to join game`. I take it you don't see the lobby on Crime.net, but are joining via steam invite?

> The game is at U103 now,with Rust being released.

Rust came in U102, U103 just came out and I will need to get the update to see if new changes need to be made(new network code can cause crash if biglobby does not have it). If you want to check game version you can find it at [biglobby/lua/_custom/biglobby_globals.lua#L38](https://github.com/polarathene/biglobby/blob/master/biglobby/lua/_custom/biglobby_globals.lua#L38). Clicking that link shows you the code and highlights line, if you each check this file in text editor, you can see it is probably different number.

Easiest fix should be to remove the pdmod/blt mod and then all use the latest version linked [here](https://github.com/polarathene/biglobby/releases/tag/v2.0.0-alpha), 2.0.4 presently.

> Would that affect anything?

No, that is just english translation file for the menu. If another language is added, they get added as new file there, like es.json for spanish.

**Comment by Damakun** [comment] 2016-06-24 03:00
I checked the Lua but the text on the text editor corresponds to what line 38 says. The version of big lobby is 2.0.4 as well apparently. Also, ignore what I said about 6/17 and 6/18. It's because of my friend's and I's timezones. So,basically we all have the same version. The only person with the problem is me for some weird reason.

**Comment by polarathene** [comment] 2016-06-24 04:17
You verified that your friends also have 2.0.4 in that lua file? You only confirmed on your end from what I can tell?

You should be able to also confirm this by going onto Crime.Net in game, if your friends are all in same area of the world you shouldn't need to change the filter. The hosts lobby should appear, if you can't see it, but your other friends can, then they are using a different version. If lots of lobbies appear for one of you, that person probably does not have the BigLobby mod enabled. I'm assuming you have been joining via Steam join request, checking Crime.Net like described is probably the easiest way for you all to check if something is wrong. 

If you can see the lobby on Crime.Net but cannot join, that would be odd.

**Comment by berki94** [comment] 2016-06-24 10:09
Sorry bro but this not working :( We playing 2 minutes and game crashing

**Comment by polarathene** [comment] 2016-06-24 11:14
@berki94 Are you part of group with @Damakun or different? @Damakun cannot join his friends lobby, you're saying you're able to play.

If you can play, make sure you are using version 2.0.4--alpha, I explain above things to check for why game is not working. If you had it working before update to U103, make sure you disable pdmod, verify cache then apply pdmod again. If still crashing it's because of U103 update changing network code. I will fix but updating game takes many hours for me.

**Comment by Damakun** [comment] 2016-06-24 18:13
That guy is in a different group from me (I think). Anyways, I got confirmation from my friends that they're doing a different version. Theirs is 2.0.2. So I think my problem can be solved by either me installing 2.0.2 or them installing 2.0.4. (unfortunately they're crashing a lot so I'm going to do the prior. We'll install the latest version once you update it.) Thanks for the help though.

**Comment by polarathene** [comment] 2016-06-24 22:48
@Damakun yes, don't use older versions, if you go to the release page I linked above, it says what bugs were fixed, they usually are crash fixes, so playing old version will not be good :)

**Comment by Damakun** [comment] 2016-06-25 04:14
It's more of the latest version crashes their game (for some reason.) Not the other way around.

**Comment by polarathene** [comment] 2016-06-25 04:38
@Damakun `2.0.2--alpha` will crash too because of bad network commands and spawning sentries will crash players. If you are getting crash with `2.0.4--alpha`, it is probably because of latest game update, I am downloading it but it takes many hours for me. Should have `2.0.5--alpha` released in 6 or so hours.

If you want to help make sure I fix any crash you're having I need crashlog. [Here is guide](https://steamcommunity.com/app/218620/discussions/14/530645446323387705/) to get that for me.

**Comment by polarathene** [comment] 2016-06-25 11:40
@berki94 @Damakun Please try [`2.0.5--alpha`](https://github.com/polarathene/biglobby/releases/download/v2.0.0-alpha/biglobby-2.0.5-alpha.zip) and let me know if it works good now :)

If still problems please share crashlog so I can fix, cheers!

**Comment by polarathene** [comment] 2016-07-09 01:25
Closing, no response.

**Closed as completed by polarathene** 2016-07-09 01:25 UTC
